### PR TITLE
Translation Update

### PR DESCRIPTION
**Pull request by llchrisll**
- Translated nearly every "jRO Item" in itemInfo_true_V5.lua, which got "corrupted" with EUC-KR encoding, which made it uneditable.
- Translated Abyss Glastheim Items
- Translated Magma Dungeon F3 items
- Translated Old Glastheim Hard Quests
- Translated Soul Reaper and Star Emperor Skills as well as the Buff Icon Descriptions
- Translated Lapine UI System
- Added missing items since your last update
- Small data folder sync

### CODE REVIEW

**Comment by zackdreaver** [comment]
I like this PR, though i can't review and test all of them wholly,
Iet me know if you want to add more file or not, I'll merge it in a few days.

**Comment by llchrisll** [comment]
Well currently I don't have much time to continue reshaping, but my next one would be syncing soul reaper and star emperor skills with your WIP files xX
But I'm not sure either if you are finished already with the skills update themself.

**Comment by zackdreaver** [comment]
Nah, my time is limited too, even I'm considering dropping this project, so there will be no more update from me for a while.

Well then , if there really nothing to add, I'll merge it tomorrow.

**Comment by llchrisll** [comment]
So my discord is Houndeye#2924

**Comment by zackdreaver** [comment]
I don't use discord.

This project is free for everyone to use or modify, just give me credit if it my work/project.

**Comment by zackdreaver** [comment]
Thank you for your contribution

**Comment by llchrisll** [comment]
Anything else for pming? Cuz when you quit this project, I would take over it. So either I copy it directly and make a separate one so you can delete yours or you transfer the ownership of it to me or anyone else, who is interested. Once you wanna come back I would transfer it back ofc. That's what I wanted to ask you directly...

**Pull request merged**
