### PR TITLE
Fix langtype 1 on sclientinfo.xml on newer clients

### PR DESCRIPTION
**Pull request by Mikegyver**
Fix langtype 1 on sclientinfo.xml on 2017-06-28bRagexeRE & newer RE
clients. Thanks to @Rytech2 for the lua file.

### CODE REVIEW

**Comment by Daegaladh** [comment]
I thought you only need that one when you have `<servicetype>america</servicetype>`, not with langtype 1 D:

**Comment by Mikegyver** [comment]
well.. lots of changes happen i guess.. as long as this fix the error in langtype 1 in the sclientinfo.xml for 2017-06-28bRagexeRE & newer RE clients... it is kinda relieve this error has gone. xD

---------------------------
GetTableIntValueForC
---------------------------
attempt to call a nil value

---------------------------
OK   
---------------------------

**Comment by zackdreaver** [comment]
I don't have this client, I can't test if this PR will do any fix.

**Comment by Mikegyver** [comment]
@zackdreaver u can get them from here.

http://herc.ws/board/topic/15348-kro-unpacked-clients-releases/

**Comment by zackdreaver** [comment]
I'll announce my standpoint regarding newer clients (2017-06-28 and up) in forum later.
There are many issues with new clients, and this is only a small one.

**Comment by zackdreaver** [comment]
I've updated README.md regarding newer clients,
thank you for your understanding.

**Pull request closed without merging**
