### PR TITLE
Updated skillinfolist.lub and changed skill names to iRO's (with fixes)

### PR DESCRIPTION
**Pull request by Daegaladh**

### CODE REVIEW

**Comment by zackdreaver** [comment]
Using kRO skill name was my decision years ago.
Personally I don't really like iRO translation.

Feel free to create a subfolder, where people can use iRO skill name, and I will merge it.

**Comment by Daegaladh** [comment]
What about just renaming it to skillinfolist_iRO.lub?

**Comment by zackdreaver** [comment]
You need to edit skill name in skilldescript.lub too, not just skillinfolist.
That's why I prefer a subfolder.

**Comment by Daegaladh** [comment]
Well, do whatever you want then.

**Pull request closed without merging**
