### PR TITLE
iteminfo english translation

### PR DESCRIPTION
**Pull request by hendra814**
update english translation for some items

### CODE REVIEW

**Comment by zackdreaver** [comment]
You're breaking all item resource names, please correct your git client encoding.

**Comment by zackdreaver** [comment]
And please, follow this project's standard in creating item description, especially with color.

**Comment by hendra814** [comment]
sorry, so i must put all file to create pull request?
this is my first time doing pull request.

**Comment by zackdreaver** [comment]
I'll take over this PR with next release.
Thank you for your contribution.

**Pull request closed without merging**
