### PR TITLE
corrected images

### PR DESCRIPTION
**Pull request by MegamiNoBisho**
added totem and over_totem bitmap

### CODE REVIEW

**Comment by zackdreaver** [comment]
Which client that use it
and give me screen shot if those client need it

**Comment by MegamiNoBisho** [comment]
screenbillboard001
all of it i guess? cause it tries to read the totem.bmp instead of style.bmp currently using 20151029 and 20151104 client

**Comment by zackdreaver** [comment]
Can you leave style image as it is without renamed them.
Just make a copy for totem one instead. thanks

**Comment by MegamiNoBisho** [comment]
ok just decline my pull request and so that i could send another pull request for it

**Pull request closed without merging**
